version: '3.8'

services:
  matrix-to:
    container_name: Matrix-to
    image: domoel/matrix-to:latest
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PORT=5000
